# Generated by Django 5.0 on 2026-03-15 18:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.IntegerField(blank=True, choices=[(9, '9th Grade'), (10, '10th Grade')], help_text="Student's current grade (9th or 10th)", null=True, validators=[django.core.validators.MinValueValidator(9), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
