# Generated by Django 5.0 on 2026-03-15 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoubtSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('mathematics', 'Mathematics'), ('physics', 'Physics'), ('chemistry', 'Chemistry'), ('biology', 'Biology')], help_text='Subject of the doubt', max_length=20)),
                ('title', models.CharField(help_text='Brief description of the doubt', max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved'), ('archived', 'Archived')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(help_text='The student who created this doubt session', on_delete=django.db.models.deletion.CASCADE, related_name='doubt_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Doubt Session',
                'verbose_name_plural': 'Doubt Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('student', 'Student'), ('ai', 'AI Assistant')], help_text='Who sent this message', max_length=10)),
                ('content', models.TextField(help_text='The actual message content')),
                ('image', models.ImageField(blank=True, help_text='Optional image attachment', null=True, upload_to='doubt_images/')),
                ('ai_model', models.CharField(blank=True, help_text='AI model used (e.g., claude-3-sonnet)', max_length=50)),
                ('tokens_used', models.IntegerField(blank=True, help_text='Tokens consumed in AI response', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(help_text='The doubt session this message belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='doubts.doubtsession')),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='doubtsession',
            index=models.Index(fields=['student', '-created_at'], name='doubts_doub_student_4c7ff1_idx'),
        ),
        migrations.AddIndex(
            model_name='doubtsession',
            index=models.Index(fields=['subject', 'status'], name='doubts_doub_subject_81716e_idx'),
        ),
    ]
