# Generated by Django 5.0 on 2026-03-15 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doubts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(help_text='The question text')),
                ('option_a', models.CharField(max_length=500)),
                ('option_b', models.CharField(max_length=500)),
                ('option_c', models.CharField(max_length=500)),
                ('option_d', models.CharField(max_length=500)),
                ('correct_answer', models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D')], help_text='The correct answer (A, B, C, or D)', max_length=1)),
                ('explanation', models.TextField(help_text='Detailed explanation of the answer')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10)),
                ('topic', models.CharField(blank=True, help_text='Specific topic covered', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('times_attempted', models.IntegerField(default=0, help_text='How many times this question was attempted')),
                ('times_correct', models.IntegerField(default=0, help_text='How many times it was answered correctly')),
                ('related_session', models.ForeignKey(help_text='The doubt session this question is based on', on_delete=django.db.models.deletion.CASCADE, related_name='practice_questions', to='doubts.doubtsession')),
            ],
            options={
                'verbose_name': 'Practice Question',
                'verbose_name_plural': 'Practice Questions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer', models.CharField(help_text='The answer the student selected', max_length=1)),
                ('is_correct', models.BooleanField(help_text='Whether the answer was correct')),
                ('time_taken_seconds', models.IntegerField(blank=True, help_text='Time taken to answer in seconds', null=True)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_attempts', to='practice.practicequestion')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Answer',
                'verbose_name_plural': 'Student Answers',
                'ordering': ['-attempted_at'],
                'unique_together': {('student', 'question', 'attempted_at')},
            },
        ),
    ]
