# Generated by Django 5.0 on 2026-03-15 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscussionThread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('mathematics', 'Mathematics'), ('physics', 'Physics'), ('chemistry', 'Chemistry'), ('biology', 'Biology'), ('general', 'General Discussion')], max_length=20)),
                ('title', models.CharField(help_text='Thread title/question', max_length=200)),
                ('content', models.TextField(help_text='Detailed description or question')),
                ('views_count', models.IntegerField(default=0, help_text='Number of times this thread was viewed')),
                ('is_pinned', models.BooleanField(default=False, help_text='Pinned threads appear at top')),
                ('is_locked', models.BooleanField(default=False, help_text="Locked threads don't allow new replies")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(help_text='Student who created this thread', on_delete=django.db.models.deletion.CASCADE, related_name='threads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Discussion Thread',
                'verbose_name_plural': 'Discussion Threads',
                'ordering': ['-is_pinned', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ThreadReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Reply content')),
                ('image', models.ImageField(blank=True, null=True, upload_to='community_images/')),
                ('is_solution', models.BooleanField(default=False, help_text='Mark if this reply solves the thread question')),
                ('is_hidden', models.BooleanField(default=False, help_text='Hidden replies (for moderation)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_replies', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(help_text='The thread this reply belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='community.discussionthread')),
                ('upvotes', models.ManyToManyField(blank=True, help_text='Students who upvoted this reply', related_name='upvoted_replies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Thread Reply',
                'verbose_name_plural': 'Thread Replies',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='discussionthread',
            index=models.Index(fields=['subject', '-created_at'], name='community_d_subject_aff846_idx'),
        ),
    ]
